//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidZip.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidZip.Localization.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add directory.
        /// </summary>
        internal static string AddDirectory {
            get {
                return ResourceManager.GetString("AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All folders.
        /// </summary>
        internal static string AllDirectoriesMenuItem {
            get {
                return ResourceManager.GetString("AllDirectoriesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Zip.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string ArchiveMenuItem {
            get {
                return ResourceManager.GetString("ArchiveMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create directory here.
        /// </summary>
        internal static string CannotCreateDirectoryHere {
            get {
                return ResourceManager.GetString("CannotCreateDirectoryHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization was changes, but not all UI elements was updated, you need to reload to set localization succesefully .
        /// </summary>
        internal static string ChangeLocalizationWarning {
            get {
                return ResourceManager.GetString("ChangeLocalizationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme.
        /// </summary>
        internal static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change application theme.
        /// </summary>
        internal static string ChangeThemeTooltip {
            get {
                return ResourceManager.GetString("ChangeThemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact to the support.
        /// </summary>
        internal static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create archive.
        /// </summary>
        internal static string CreateArchive {
            get {
                return ResourceManager.GetString("CreateArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        internal static string CreateDirectory {
            get {
                return ResourceManager.GetString("CreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file.
        /// </summary>
        internal static string CreateFile {
            get {
                return ResourceManager.GetString("CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string CreateMenuItem {
            get {
                return ResourceManager.GetString("CreateMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder already exists.
        /// </summary>
        internal static string DirectoryAlreadyExists {
            get {
                return ResourceManager.GetString("DirectoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string DirectoryMenuItem {
            get {
                return ResourceManager.GetString("DirectoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder must not end with &quot;.&quot;.
        /// </summary>
        internal static string DirectoryMustNotEndsWithDot {
            get {
                return ResourceManager.GetString("DirectoryMustNotEndsWithDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory using reserved strings.
        /// </summary>
        internal static string DirectoryUsingReservedString {
            get {
                return ResourceManager.GetString("DirectoryUsingReservedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not close.
        /// </summary>
        internal static string DoNotClose {
            get {
                return ResourceManager.GetString("DoNotClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditMenuItem {
            get {
                return ResourceManager.GetString("EditMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit theme.
        /// </summary>
        internal static string EditTheme {
            get {
                return ResourceManager.GetString("EditTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypttion.
        /// </summary>
        internal static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Settings.
        /// </summary>
        internal static string ExplorerSettings {
            get {
                return ResourceManager.GetString("ExplorerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure file explorer behavior.
        /// </summary>
        internal static string ExplorerSettingsTooltip {
            get {
                return ResourceManager.GetString("ExplorerSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer View.
        /// </summary>
        internal static string ExplorerViewStyle {
            get {
                return ResourceManager.GetString("ExplorerViewStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how files are displayed in explorer.
        /// </summary>
        internal static string ExplorerViewStyleTooltip {
            get {
                return ResourceManager.GetString("ExplorerViewStyleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Display Settings.
        /// </summary>
        internal static string FileDisplaySettings {
            get {
                return ResourceManager.GetString("FileDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure how files are displayed.
        /// </summary>
        internal static string FileDisplaySettingsTooltip {
            get {
                return ResourceManager.GetString("FileDisplaySettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenuItem {
            get {
                return ResourceManager.GetString("FileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must not end with &quot;.&quot;.
        /// </summary>
        internal static string FileMustNotEndWithDot {
            get {
                return ResourceManager.GetString("FileMustNotEndWithDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size Display.
        /// </summary>
        internal static string FileSizeDisplay {
            get {
                return ResourceManager.GetString("FileSizeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select format for file size display.
        /// </summary>
        internal static string FileSizeDisplayTooltip {
            get {
                return ResourceManager.GetString("FileSizeDisplayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File using reserved strings.
        /// </summary>
        internal static string FileUsingReservedStrings {
            get {
                return ResourceManager.GetString("FileUsingReservedStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input folder name.
        /// </summary>
        internal static string InsertDirectoryName {
            get {
                return ResourceManager.GetString("InsertDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file name.
        /// </summary>
        internal static string InsertFileName {
            get {
                return ResourceManager.GetString("InsertFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobytes (KB).
        /// </summary>
        internal static string Kilobytes {
            get {
                return ResourceManager.GetString("Kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        internal static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure application language settings.
        /// </summary>
        internal static string LanguageSettingsTooltip {
            get {
                return ResourceManager.GetString("LanguageSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select application language.
        /// </summary>
        internal static string LanguageTooltip {
            get {
                return ResourceManager.GetString("LanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ListMenuItem {
            get {
                return ResourceManager.GetString("ListMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application data:.
        /// </summary>
        internal static string LoadAppData {
            get {
                return ResourceManager.GetString("LoadAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading configuration....
        /// </summary>
        internal static string LoadConfiguration {
            get {
                return ResourceManager.GetString("LoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building dependencies....
        /// </summary>
        internal static string LoadDependencies {
            get {
                return ResourceManager.GetString("LoadDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting logger....
        /// </summary>
        internal static string LoadLogger {
            get {
                return ResourceManager.GetString("LoadLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading lua.
        /// </summary>
        internal static string LoadLua {
            get {
                return ResourceManager.GetString("LoadLua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua&apos;s plugins.
        /// </summary>
        internal static string LuaPlugins {
            get {
                return ResourceManager.GetString("LuaPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabytes (MB).
        /// </summary>
        internal static string Megabytes {
            get {
                return ResourceManager.GetString("Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        internal static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is too long.
        /// </summary>
        internal static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use spefical charecters in the name.
        /// </summary>
        internal static string NameUsingsInvalidCharecters {
            get {
                return ResourceManager.GetString("NameUsingsInvalidCharecters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to SolidZip&apos;s settings?.
        /// </summary>
        internal static string NeedToSaveChanges {
            get {
                return ResourceManager.GetString("NeedToSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string NewDirectory {
            get {
                return ResourceManager.GetString("NewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new-folder.
        /// </summary>
        internal static string NewDirectoryName {
            get {
                return ResourceManager.GetString("NewDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        internal static string NewFileMenuItem {
            get {
                return ResourceManager.GetString("NewFileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New zip.
        /// </summary>
        internal static string NewZip {
            get {
                return ResourceManager.GetString("NewZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open via windows explorer.
        /// </summary>
        internal static string OpenViaWindowsExplorer {
            get {
                return ResourceManager.GetString("OpenViaWindowsExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing...
        /// </summary>
        internal static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string RedoMenuItem {
            get {
                return ResourceManager.GetString("RedoMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove directory.
        /// </summary>
        internal static string RemoveDirectory {
            get {
                return ResourceManager.GetString("RemoveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameMenuItem {
            get {
                return ResourceManager.GetString("RenameMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to default values.
        /// </summary>
        internal static string ResetToDefaultsTooltip {
            get {
                return ResourceManager.GetString("ResetToDefaultsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Files.
        /// </summary>
        internal static string SampleFiles {
            get {
                return ResourceManager.GetString("SampleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example files for preview.
        /// </summary>
        internal static string SampleFilesTooltip {
            get {
                return ResourceManager.GetString("SampleFilesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all current settings.
        /// </summary>
        internal static string SaveChangesTooltip {
            get {
                return ResourceManager.GetString("SaveChangesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory.
        /// </summary>
        internal static string SelectDirectory {
            get {
                return ResourceManager.GetString("SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected files.
        /// </summary>
        internal static string SelectedFiles {
            get {
                return ResourceManager.GetString("SelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how file sizes are shown.
        /// </summary>
        internal static string SelectFileSizeDisplayTooltip {
            get {
                return ResourceManager.GetString("SelectFileSizeDisplayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file from the list.
        /// </summary>
        internal static string SelectFileTooltip {
            get {
                return ResourceManager.GetString("SelectFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred language.
        /// </summary>
        internal static string SelectLanguageTooltip {
            get {
                return ResourceManager.GetString("SelectLanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectMenuItem {
            get {
                return ResourceManager.GetString("SelectMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output folder.
        /// </summary>
        internal static string SelectOutputFolder {
            get {
                return ResourceManager.GetString("SelectOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file display style.
        /// </summary>
        internal static string SelectViewStyleTooltip {
            get {
                return ResourceManager.GetString("SelectViewStyleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ServicesMenuItem {
            get {
                return ResourceManager.GetString("ServicesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set archive name.
        /// </summary>
        internal static string SetArchiveName {
            get {
                return ResourceManager.GetString("SetArchiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden Directories.
        /// </summary>
        internal static string ShowHiddenDirectories {
            get {
                return ResourceManager.GetString("ShowHiddenDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display hidden files and folders.
        /// </summary>
        internal static string ShowHiddenDirectoriesTooltip {
            get {
                return ResourceManager.GetString("ShowHiddenDirectoriesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show history.
        /// </summary>
        internal static string ShowHistoryMenuItem {
            get {
                return ResourceManager.GetString("ShowHistoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in windows explorer.
        /// </summary>
        internal static string ShowInWindowsExplorerMenuItem {
            get {
                return ResourceManager.GetString("ShowInWindowsExplorerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show logs.
        /// </summary>
        internal static string ShowLogs {
            get {
                return ResourceManager.GetString("ShowLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Lua Console.
        /// </summary>
        internal static string ShowLuaConsole {
            get {
                return ResourceManager.GetString("ShowLuaConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide the Lua scripting console.
        /// </summary>
        internal static string ShowLuaConsoleTooltip {
            get {
                return ResourceManager.GetString("ShowLuaConsoleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string TableMenuItems {
            get {
                return ResourceManager.GetString("TableMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Settings.
        /// </summary>
        internal static string ThemeSettings {
            get {
                return ResourceManager.GetString("ThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change application theme and appearance.
        /// </summary>
        internal static string ThemeSettingsTooltip {
            get {
                return ResourceManager.GetString("ThemeSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has no access to open this folder.
        /// </summary>
        internal static string UnauthorizedAccessText {
            get {
                return ResourceManager.GetString("UnauthorizedAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string UndoMenuItem {
            get {
                return ResourceManager.GetString("UndoMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured, application cannot work anymore and need to restart.
        /// </summary>
        internal static string UnexpectedErrorText {
            get {
                return ResourceManager.GetString("UnexpectedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewMenuItem {
            get {
                return ResourceManager.GetString("ViewMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your folder name.
        /// </summary>
        internal static string WriteNewDirectoryName {
            get {
                return ResourceManager.GetString("WriteNewDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Archive.
        /// </summary>
        internal static string ZipFile {
            get {
                return ResourceManager.GetString("ZipFile", resourceCulture);
            }
        }
    }
}
