//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidZip.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidZip.Localization.Resources.Localization.ru-RU", typeof(Localization_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить папку.
        /// </summary>
        internal static string AddDirectory {
            get {
                return ResourceManager.GetString("AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все папки.
        /// </summary>
        internal static string AllDirectoriesMenuItem {
            get {
                return ResourceManager.GetString("AllDirectoriesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все файлы.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Архиватор.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив.
        /// </summary>
        internal static string ArchiveMenuItem {
            get {
                return ResourceManager.GetString("ArchiveMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Байты.
        /// </summary>
        internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно создать папку здесь.
        /// </summary>
        internal static string CannotCreateDirectoryHere {
            get {
                return ResourceManager.GetString("CannotCreateDirectoryHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык был изменен, но не все компоненты были обновлены, для полноценной работы перевода нужна перезагрузка.
        /// </summary>
        internal static string ChangeLocalizationWarning {
            get {
                return ResourceManager.GetString("ChangeLocalizationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить тему.
        /// </summary>
        internal static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите, чтобы изменить тему приложения.
        /// </summary>
        internal static string ChangeThemeTooltip {
            get {
                return ResourceManager.GetString("ChangeThemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратиться в поддержку.
        /// </summary>
        internal static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать архив.
        /// </summary>
        internal static string CreateArchive {
            get {
                return ResourceManager.GetString("CreateArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать папку.
        /// </summary>
        internal static string CreateDirectory {
            get {
                return ResourceManager.GetString("CreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string CreateMenuItem {
            get {
                return ResourceManager.GetString("CreateMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка уже существует.
        /// </summary>
        internal static string DirectoryAlreadyExists {
            get {
                return ResourceManager.GetString("DirectoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папку.
        /// </summary>
        internal static string DirectoryMenuItem {
            get {
                return ResourceManager.GetString("DirectoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка не должна заканчиваться на &quot;.&quot;.
        /// </summary>
        internal static string DirectoryMustNotEndsWithDot {
            get {
                return ResourceManager.GetString("DirectoryMustNotEndsWithDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка использует зарезервированные Windows названия.
        /// </summary>
        internal static string DirectoryUsingReservedString {
            get {
                return ResourceManager.GetString("DirectoryUsingReservedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не закрывать.
        /// </summary>
        internal static string DoNotClose {
            get {
                return ResourceManager.GetString("DoNotClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        internal static string EditMenuItem {
            get {
                return ResourceManager.GetString("EditMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать тему.
        /// </summary>
        internal static string EditTheme {
            get {
                return ResourceManager.GetString("EditTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шифрование.
        /// </summary>
        internal static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки проводника.
        /// </summary>
        internal static string ExplorerSettings {
            get {
                return ResourceManager.GetString("ExplorerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка поведения проводника файлов.
        /// </summary>
        internal static string ExplorerSettingsTooltip {
            get {
                return ResourceManager.GetString("ExplorerSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид проводника.
        /// </summary>
        internal static string ExplorerViewStyle {
            get {
                return ResourceManager.GetString("ExplorerViewStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите способ отображения файлов в проводнике.
        /// </summary>
        internal static string ExplorerViewStyleTooltip {
            get {
                return ResourceManager.GetString("ExplorerViewStyleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки отображения файлов.
        /// </summary>
        internal static string FileDisplaySettings {
            get {
                return ResourceManager.GetString("FileDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка отображения файлов.
        /// </summary>
        internal static string FileDisplaySettingsTooltip {
            get {
                return ResourceManager.GetString("FileDisplaySettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string FileMenuItem {
            get {
                return ResourceManager.GetString("FileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображение размера файлов.
        /// </summary>
        internal static string FileSizeDisplay {
            get {
                return ResourceManager.GetString("FileSizeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите формат отображения размера файлов.
        /// </summary>
        internal static string FileSizeDisplayTooltip {
            get {
                return ResourceManager.GetString("FileSizeDisplayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сетка.
        /// </summary>
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название папки.
        /// </summary>
        internal static string InsertDirectoryName {
            get {
                return ResourceManager.GetString("InsertDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Килобайты (КБ).
        /// </summary>
        internal static string Kilobytes {
            get {
                return ResourceManager.GetString("Kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки языка.
        /// </summary>
        internal static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки языка приложения.
        /// </summary>
        internal static string LanguageSettingsTooltip {
            get {
                return ResourceManager.GetString("LanguageSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык приложения.
        /// </summary>
        internal static string LanguageTooltip {
            get {
                return ResourceManager.GetString("LanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список.
        /// </summary>
        internal static string ListMenuItem {
            get {
                return ResourceManager.GetString("ListMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных приложения:.
        /// </summary>
        internal static string LoadAppData {
            get {
                return ResourceManager.GetString("LoadAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка конфигурации....
        /// </summary>
        internal static string LoadConfiguration {
            get {
                return ResourceManager.GetString("LoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создаем зависимости....
        /// </summary>
        internal static string LoadDependencies {
            get {
                return ResourceManager.GetString("LoadDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключаем журналирование....
        /// </summary>
        internal static string LoadLogger {
            get {
                return ResourceManager.GetString("LoadLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка Lua плагинов...
        /// </summary>
        internal static string LoadLua {
            get {
                return ResourceManager.GetString("LoadLua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плагины Lua.
        /// </summary>
        internal static string LuaPlugins {
            get {
                return ResourceManager.GetString("LuaPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мегабайты (МБ).
        /// </summary>
        internal static string Megabytes {
            get {
                return ResourceManager.GetString("Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название не может быть пустым.
        /// </summary>
        internal static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название слишком длинное.
        /// </summary>
        internal static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя использовать специальные символы в названии.
        /// </summary>
        internal static string NameUsingsInvalidCharecters {
            get {
                return ResourceManager.GetString("NameUsingsInvalidCharecters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения в настройках Zip Архиватора?.
        /// </summary>
        internal static string NeedToSaveChanges {
            get {
                return ResourceManager.GetString("NeedToSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая Папка.
        /// </summary>
        internal static string NewDirectory {
            get {
                return ResourceManager.GetString("NewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to новая-папка.
        /// </summary>
        internal static string NewDirectoryName {
            get {
                return ResourceManager.GetString("NewDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый zip архив.
        /// </summary>
        internal static string NewZip {
            get {
                return ResourceManager.GetString("NewZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть с помощью Windows Explorer.
        /// </summary>
        internal static string OpenViaWindowsExplorer {
            get {
                return ResourceManager.GetString("OpenViaWindowsExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка....
        /// </summary>
        internal static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторить.
        /// </summary>
        internal static string RedoMenuItem {
            get {
                return ResourceManager.GetString("RedoMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить папку.
        /// </summary>
        internal static string RemoveDirectory {
            get {
                return ResourceManager.GetString("RemoveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переменовать.
        /// </summary>
        internal static string RenameMenuItem {
            get {
                return ResourceManager.GetString("RenameMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить настройки.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить все настройки к значениям по умолчанию.
        /// </summary>
        internal static string ResetToDefaultsTooltip {
            get {
                return ResourceManager.GetString("ResetToDefaultsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примеры файлов.
        /// </summary>
        internal static string SampleFiles {
            get {
                return ResourceManager.GetString("SampleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примеры файлов для предпросмотра.
        /// </summary>
        internal static string SampleFilesTooltip {
            get {
                return ResourceManager.GetString("SampleFilesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить все текущие настройки.
        /// </summary>
        internal static string SaveChangesTooltip {
            get {
                return ResourceManager.GetString("SaveChangesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете папку.
        /// </summary>
        internal static string SelectDirectory {
            get {
                return ResourceManager.GetString("SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранные файлы.
        /// </summary>
        internal static string SelectedFiles {
            get {
                return ResourceManager.GetString("SelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите, как отображать размеры файлов.
        /// </summary>
        internal static string SelectFileSizeDisplayTooltip {
            get {
                return ResourceManager.GetString("SelectFileSizeDisplayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл из списка.
        /// </summary>
        internal static string SelectFileTooltip {
            get {
                return ResourceManager.GetString("SelectFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите предпочтительный язык.
        /// </summary>
        internal static string SelectLanguageTooltip {
            get {
                return ResourceManager.GetString("SelectLanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        internal static string SelectMenuItem {
            get {
                return ResourceManager.GetString("SelectMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите папку для размещения архива.
        /// </summary>
        internal static string SelectOutputFolder {
            get {
                return ResourceManager.GetString("SelectOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите стиль отображения файлов.
        /// </summary>
        internal static string SelectViewStyleTooltip {
            get {
                return ResourceManager.GetString("SelectViewStyleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервисы.
        /// </summary>
        internal static string ServicesMenuItem {
            get {
                return ResourceManager.GetString("ServicesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите имя архива.
        /// </summary>
        internal static string SetArchiveName {
            get {
                return ResourceManager.GetString("SetArchiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать скрытые папки.
        /// </summary>
        internal static string ShowHiddenDirectories {
            get {
                return ResourceManager.GetString("ShowHiddenDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать скрытые файлы и папки.
        /// </summary>
        internal static string ShowHiddenDirectoriesTooltip {
            get {
                return ResourceManager.GetString("ShowHiddenDirectoriesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать историю.
        /// </summary>
        internal static string ShowHistoryMenuItem {
            get {
                return ResourceManager.GetString("ShowHistoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать в windows explorer.
        /// </summary>
        internal static string ShowInWindowsExplorerMenuItem {
            get {
                return ResourceManager.GetString("ShowInWindowsExplorerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать журналы.
        /// </summary>
        internal static string ShowLogs {
            get {
                return ResourceManager.GetString("ShowLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать консоль Lua.
        /// </summary>
        internal static string ShowLuaConsole {
            get {
                return ResourceManager.GetString("ShowLuaConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать/скрыть консоль скриптов Lua.
        /// </summary>
        internal static string ShowLuaConsoleTooltip {
            get {
                return ResourceManager.GetString("ShowLuaConsoleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица.
        /// </summary>
        internal static string TableMenuItems {
            get {
                return ResourceManager.GetString("TableMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темы.
        /// </summary>
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки темы.
        /// </summary>
        internal static string ThemeSettings {
            get {
                return ResourceManager.GetString("ThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить тему и внешний вид приложения.
        /// </summary>
        internal static string ThemeSettingsTooltip {
            get {
                return ResourceManager.GetString("ThemeSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно прав дляоткрытие этой папки.
        /// </summary>
        internal static string UnauthorizedAccessText {
            get {
                return ResourceManager.GetString("UnauthorizedAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string UndoMenuItem {
            get {
                return ResourceManager.GetString("UndoMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла неожиданная ошибка, приложените более не может работать и нуждается в перезагрузке.
        /// </summary>
        internal static string UnexpectedErrorText {
            get {
                return ResourceManager.GetString("UnexpectedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизевестно.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        internal static string ViewMenuItem {
            get {
                return ResourceManager.GetString("ViewMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название папки.
        /// </summary>
        internal static string WriteNewDirectoryName {
            get {
                return ResourceManager.GetString("WriteNewDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Архив.
        /// </summary>
        internal static string ZipFile {
            get {
                return ResourceManager.GetString("ZipFile", resourceCulture);
            }
        }
    }
}
